(()=>{'use strict';const d=document;const $=(s,r=d)=>r.querySelector(s);const $$=(s,r=d)=>Array.from(r.querySelectorAll(s));
function nav(){const t=$('.nav-toggle'),l=$('.nav-links');if(!t||!l)return;t.addEventListener('click',()=>{const e=t.getAttribute('aria-expanded')==='true';t.setAttribute('aria-expanded',e?'false':'true');d.body.classList.toggle('nav-open',!e)});$$('.nav-links a,.nav-links button').forEach(x=>x.addEventListener('click',()=>{t.setAttribute('aria-expanded','false');d.body.classList.remove('nav-open')}))}
function progress(){if($('.reading-progress'))return;const b=d.createElement('div');b.className='reading-progress';b.innerHTML='<span></span>';d.body.appendChild(b);const f=b.firstElementChild;const u=()=>{const h=Math.max(1,d.documentElement.scrollHeight-innerHeight);f.style.transform='scaleX('+Math.max(0,Math.min(1,scrollY/h))+')'};u();addEventListener('scroll',u,{passive:true});addEventListener('resize',u)}
function music(){const src='lumen-nocturne.mp3',key='tagMusicStateV218';let a=$('#site-music-audio');if(!a){a=d.createElement('audio');a.id='site-music-audio';a.src=src;a.loop=true;a.preload='auto';a.playsInline=true;d.body.appendChild(a)}let state={desired:false,time:0,volume:.42};try{state={...state,...JSON.parse(localStorage.getItem(key)||'{}')}}catch{}a.volume=Math.max(0,Math.min(1,Number(state.volume)||.42));const buttons=()=>$$('#music-toggle,.music-toggle');let desired=!!state.desired;const save=()=>{try{localStorage.setItem(key,JSON.stringify({desired,time:Number.isFinite(a.currentTime)?a.currentTime:0,volume:a.volume,updatedAt:Date.now()}))}catch{}};const sync=()=>buttons().forEach(b=>{const on=!a.paused;b.setAttribute('aria-pressed',on?'true':'false');b.classList.toggle('is-playing',on);if(/music|מוזיקה/i.test(b.textContent||''))b.textContent=on?(d.documentElement.lang==='he'?'מוזיקה פועלת':'Music On'):(d.documentElement.lang==='he'?'מוזיקה':'Music')});const play=async()=>{if(!desired)return;try{await a.play()}catch{}sync();save()};if(a.readyState>=1){try{a.currentTime=Number(state.time)||0}catch{}}else a.addEventListener('loadedmetadata',()=>{try{a.currentTime=Number(state.time)||0}catch{}},{once:true});buttons().forEach(b=>b.addEventListener('click',e=>{e.preventDefault();if(desired&&!a.paused){desired=false;a.pause();save();sync()}else{desired=true;save();play()}}));['pointerdown','touchstart','keydown'].forEach(type=>d.addEventListener(type,e=>{if(e.target&&e.target.closest&&e.target.closest('#music-toggle,.music-toggle'))return;if(!desired||a.paused){desired=true;save();play()}},{capture:true,passive:type!=='keydown'}));addEventListener('pagehide',save);d.addEventListener('visibilitychange',()=>{if(d.visibilityState==='hidden')save();else if(desired&&a.paused)play()});sync();if(desired)play()}
function init(){nav();progress();music()}if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',init,{once:true});else init()})();


/* v222 service-worker registration */
if('serviceWorker' in navigator && /^https?:$/.test(location.protocol)){
  window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js?v=222').catch(()=>{}),{once:true});
}
